### ISSUE TITLE
Unnecesary min in damage calculus

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#357]
```lua
local dmg = math.max(math.min(1, amount), amount - defroll)
```
This.

**Comment by OrenjiAkira** [comment]
explain

**Comment by OrenjiAkira** [comment]
nvm i got it

**Comment by OrenjiAkira** [comment]
no wait i didn't explain

**Comment by OrenjiAkira** [comment]
if amount is zero, that means the damage will become 1 if we remove that `math.min`. That looks strange to me. So the min looks necessary to me.

**Comment by Kazuo256** [comment]
You replace the whole `min(...)` part by `1`.

**Comment by OrenjiAkira** [comment]
Again, if you got a zero from the amount, you are taking one in damage, not by defence, but because you fucked up your attack so badly that it rolled zero. You didn't even hit them. The min is there to make sure that if you fucked up this badly, you will still deal zero damage. You would only deal one damage if your attack hit them but they defended it. Thus the min is there.

**Comment by Kazuo256** [comment]
Oh, I see. So the `min`'s purpose was to deal specially with the case where `amount == 0`. I always liked using mins and maxs, but this os the first time I saw it obfuscate the code's intention.

In that case. I suggest we either add a comment explaining it, or we just return out of the function if `amount <= 0` because we don't want to trigger anything damage-related in that scenario anyway.

**Comment by OrenjiAkira** [comment]
that sounds fair

(But on a side note, just musing this possibility: what if there is a level of resistence that is "absorb"? in this scenario, resistances are multiplications. Res `lvl1` is `1/2 dmg`, res `lvl2` is `1/4 dmg`, res `lvl3` is `*0`. Aaaand, absorb or res `lvl4` is `*-1`.)

**Comment by Kazuo256** [comment]
(it seems highly exploitable, which could be very fun XD)
