### ISSUE TITLE
Drop "play points" mechanics

### ISSUE THREAD

**Issue by Kazuo256** [uspgamedev/backdoor#522]
I feel like it wouldn't take anything out of the gameplay, except make it simpler. The only adjustment is that hands would be drawn automatically when the previous ended.

Also, this might make @marcheing happy.

**Comment by rilifon** [comment]
I vote we test this. Play points are really obscure in our game. The only concern is if it will easily exploitable.

Quick idea I had would be: drawing cost player life

**Comment by Kazuo256** [comment]
> The only concern is if it will easily exploitable.

Yeah, you have a point, I can already think of one exploit: stash you cards endlessly and cast a stupidly hot fireball. This happens because stashing costs only time (and very little at that).

> Quick idea I had would be: drawing cost player life

That's a possible solution. Quickly analyzing it:
1. The cost would have to be in life percentual, otherwise grinding VIT would be OP
2. It comboes with healing effects, which might or might not be desirable
3. It heaviliy penalizes players in dire situations at low HP

I'll try to come up with more alternatives we can test to find the most appropriate.

**Comment by OrenjiAkira** [comment]
1 and 2 are fine, though I think that "grinding VIT" is a valid strategy (it's not that easy to get HP via VIT anyway). But 3 is particularly bad, because quickly going through your buffer in dire-low-HP situations is vital and necessary.

If stashing stuff endlessly without cost is a problem a quick-fix solution is to make drawing a new hand execute the "ON_ACT" trigger, though that has other ramifications as well.

**Comment by Kazuo256** [comment]
(I wrote most of this before @OrenjiAkira's post)

Thinking about it, the idea of drawing hands automatically is very dangerous indeed. We don't want (I imagine) the player cylcing the whole deck too easily. There must be a restriction or a cost.

Right now, the "expendable resources" we have if we take play points out are hit points, experience, and exhaustion (time). Of these, hit points really are the most viable, because experience is too hard to get and exhaustion doesn't really stop the player from cycling the whole deck in safe areas.

However, with item (2) in my previous message, I think cycling the whole deck is still not too far away. Just cast Meditate, stay still and stash away your whole deck as much as you want.

I'm not sure using HP is the problem here though. The same could happen with play points because playing cards generate them. That is, if your deck only has cards that give 2 or more play points (10+ per hand), then you are never out of hands after your first one. The difference is that you actually have to play the cards, not only stash them.

So I think the main problem is that cards shouldn't guarantee more hands unless by design. Using HP as cost makes that hard, but using play points doesn't quite solve it.

This is hard.

(here is after @OrenjiAkira's post)

> If stashing stuff endlessly without cost is a problem a quick-fix solution is to make drawing a new hand execute the "ON_ACT" trigger, though that has other ramifications as well.

Another quick-fix solution is to make stash cards discharge with time again. I little sad, but still OK.

But I don't think stashing too much is the only problem.

**Comment by OrenjiAkira** [comment]
I think that, if the player is somewhere safe, there is no point in not allowing them to cycle through their buffer. First and foremost because Upgrading attributes mid-battle is terrible, and those safe-times are best for looking for that upgrade you've been saving.

Auto-drawing from buffer, however, is indeed too easy when mid-battle, and in general a bad idea when you want to be able to manage your back buffer. If drawing a buffer is only OP during encounters, then make it cost a hella long time (3 turns or so! If you try this mid-battle you're dead! Plus drawing would spend stash bonuses in this case. The "Calming" healing card would also be spent by this, if we want the cost to be HP instead of just time.)

We need, regardless of everything, feedback of when drawing a card will shuffle your buffer. (Maybe drawing effects don't work when you don't have a "ready" buffer? This would facilitate managing the backbuffer/buffer state). This is important because auto-drawing messes this up completely, and it's nice knowing fast and easy when you have a backbuffer to manage or when you just need to believe in the heart of the cards to draw that one card you been waiting

**Comment by Kazuo256** [comment]
> I think that, if the player is somewhere safe, there is no point in not allowing them to cycle through their buffer. First and foremost because Upgrading attributes mid-battle is terrible, and those safe-times are best for looking for that upgrade you've been saving.

Yes, for upgrades that's necessary and fine. But I think there are some cards we don't want the player using anytime they want. For instance, if creating Sensor Bombs becomes too easy and repeatable, a player could spread Bombs along his or her path and become unaproachable. Besides, just being able to "choose" a hand to start the next encounter with might be undesirable, in the sense that not doing so is suboptimal but doing so is not fun at all. Imagine spending 10 minutes between each encounter just so you can walk around with your best hand at all times.

> We need, regardless of everything, feedback of when drawing a card will shuffle your buffer.

Yes, we do, but that's a separate issue, I believe. I'll open it.
