### ISSUE TITLE
Crash when casting card on last focus turn

### ISSUE THREAD

**Issue by OrenjiAkira** [uspgamedev/backdoor#985]
```
Error

libs/steaming/extra_libs/hump/timer.lua:48: view/transmission.lua:27: attempt to index local 'target' (a nil value)
```
Looks like a timer thing on transmission animation

**Comment by OrenjiAkira** [comment]
[debugsave.zip](https://github.com/uspgamedev/backdoor/files/2908390/debugsave.zip)
Here's the save for debugging.

**Comment by Kazuo256** [comment]
Alright, this happens when you equip a widget as your last focused action. After equiping the card, your turn ends, and so does your focus, which empties your hand. The UI still tries to animate the transmission, but the card is no longer there, so it fails.

We need to yield the turn loop before the end of the turn and carry out the animation then. I don't how hard that is to do.

On a side note, this gave me small design change idea. See (issue that doesn't exist yet)
